name: timer_count_down

version: 2.2.0

description: >
    Simple CountDown timer. Using for create a simple timer. It's pure all

homepage: https://github.com/DizoftTeam/simple_count_down

environment:
    sdk: ">=2.12.0 <3.0.0"
    flutter: ">=1.10.0"

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    lint: ^1.3.0
    pedantic: ^1.9.0
